kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
archiveSize: 4
storageConfig:
  local:
    path: /root/labs/media/ocp4.11.18
mirror:
  platform:
    architectures:
    - amd64
    channels:
    - name: stable-4.11
      type: ocp
      minVersion: 4.11.18
      maxVersion: 4.11.18
    graph: true
