kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
archiveSize: 4
storageConfig:
  local:
    path: /opt/apps/ocp4.11.18/metadata
mirror:
  platform:
    architectures:
    - amd64
    channels:
    - name: stable-4.11
      type: ocp
      minVersion: 4.11.18
      maxVersion: 4.11.18
    graph: true
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.11
    packages:
    - name: cluster-logging
      channels:
      - name: stable
    - name: compliance-operator
      channels:
      - name: release-0.1
    - name: elasticsearch-operator
      channels:
      - name: stable
    - name: local-storage-operator
      channels:
      - name: stable
    - name: servicemeshoperator
      channels:
      - name: stable
    - name: jaeger-product
      channels:
      - name: stable
    - name: kiali-ossm
      channels:
      - name: stable
    - name: rhsso-operator
      channels:
      - name: stable
    - name: openshift-gitops-operator
      channels:
      - name: latest
    - name: cincinnati-operator
      channels:
      - name: v1
  - catalog: registry.redhat.io/redhat/certified-operator-index:v4.11
    packages:
    - name: aqua-operator-certified
